[2024-04-08T02:11:37.421+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-08T02:11:36.788837+00:00 [queued]>
[2024-04-08T02:11:37.425+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-08T02:11:36.788837+00:00 [queued]>
[2024-04-08T02:11:37.426+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-08T02:11:37.432+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-04-08 02:11:36.788837+00:00
[2024-04-08T02:11:37.435+0000] {standard_task_runner.py:60} INFO - Started process 58 to run task
[2024-04-08T02:11:37.439+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-04-08T02:11:36.788837+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp66w_z1xz']
[2024-04-08T02:11:37.440+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask reddit_extraction
[2024-04-08T02:11:37.467+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-04-08T02:11:36.788837+00:00 [running]> on host e7698c345b63
[2024-04-08T02:11:37.511+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kyungmin Park' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T02:11:36.788837+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T02:11:36.788837+00:00'
[2024-04-08T02:11:37.514+0000] {logging_mixin.py:188} INFO - connected to reddit!
[2024-04-08T02:11:53.528+0000] {sessions.py:161} WARNING - Retrying due to ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.reddit.com', port=443): Max retries exceeded with url: /api/v1/access_token (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8eafa4f0>, 'Connection to www.reddit.com timed out. (connect timeout=16.0)'))")) status: GET https://oauth.reddit.com/r/dataengineering/top
[2024-04-08T02:11:56.322+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T02:11:56.336+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20240408T021136, start_date=20240408T021137, end_date=20240408T021156
[2024-04-08T02:11:56.370+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T02:11:56.387+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
